name: Deploy Contributions Snake

on:
  push:
    branches:
      - main  # change if your default branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Contributions Snake SVG
        run: |
          npx github-contributions-snake > dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output  # branch to deploy your site (change if different)
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
